In [1]:
#Some modules
import platform
x=platform.system()
print(x)
# print(dir(platform))

Windows


In [2]:
#Math moudles
import math
print(math.acos(0.55))
print(math.acos(-0.55))
print(math.acos(0))
print(math.acos(1))
print(math.acos(-1))
print(math.comb(7,5))#Items to choose from , Number of possiblities
print(math.ceil(-5.02))#Rounding off to nearest next int digit
print(math.factorial(4))
print(math.pow(2,5))
print(math.trunc(-5.45))#Return value without decimal , closer to 0
#math.e,pi,tau,inf,nan,


0.9884320889261531
2.15316056466364
1.5707963267948966
0.0
3.141592653589793
21
-5
24
32.0
-5


In [3]:
#Date time module
import datetime as dt
x=dt.datetime.now()
y=dt.datetime.now().day
z=dt.datetime.now().month
print(x,y,z)
print(x.strftime("%A"))

2026-06-02 23:07:37.779479 2 6
Tuesday


In [4]:
#Creating datetime objects
x=dt.datetime(2003,5,3)
print(x)

2003-05-03 00:00:00


In [5]:
import random
cnum=random.randrange(1,15)
unum=int(input("Enter number b/w 1 & 15:"))
if cnum>unum:
    print("Computer wins")
else:
    print("You win")
print(cnum,unum)

You win
5 5


In [6]:
import os
os.chdir('C:\\Users\\adity\\Downloads\\Coplur\\Practice\\Try')#Change to given directory
i=1
for file in os.listdir():
    src=file#Original file
    dst="Image"+str(i)+".jpg"#File to be renamed as
    os.rename(src,dst)
    i+=1
#Converted all files as Image1.jpg,image2.jpg,image3.jpg

In [7]:
#Password generator
import secrets 
import string
alphabet=string.ascii_letters + string.digits
password = "".join(secrets.choice(alphabet) for i in range(20))
print(password)


fdxPaAyYrYWz0kMFURF7


In [21]:
import qrcode
def generate_qr_code(data, filename):
    # Configure the QR code parameters
    qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_L,
        box_size=10,
        border=4,
    )
    qr.add_data(data)
    qr.make(fit=True)
    
    # Render and save the image
    img = qr.make_image(fill_color="black", back_color="white")
    img.save(filename)

if __name__ == "__main__":
    data = "https://www.example.com"
    filename = "example_qr.png"
    
    # Call the function to actually generate and save the file
    generate_qr_code(data, filename)
    print(f"QR code successfully saved as {filename}")

QR code successfully saved as example_qr.png


In [22]:
import cv2
def read_qr_code(filename):
    # Load the image
    img = cv2.imread(filename)
    # Initialize the QR code detector
    detector = cv2.QRCodeDetector()
    # Detect and decode the QR code
    data, vertices_array, binary_qrcode = detector.detectAndDecode(img)
    
    if vertices_array is not None:
        print(f"QR Code detected: {data}")
    else:
        print("No QR Code detected.")
if __name__ == "__main__":
    read_qr_code(filename)

QR Code detected: https://www.example.com


In [23]:
import qrcode
#os.chidr('<< path to file >>')
#data='https://www.red.com'
img=qrcode.make('https://www.red.com') #could also be written using data
img.save('redqr.png')

In [25]:
import cv2

detector = cv2.QRCodeDetector()
data, _, _ = detector.detectAndDecode(cv2.imread("redqr.png"))
print(f"QR Code detected: {data}" if data else "No QR Code detected.")

QR Code detected: https://www.red.com


In [26]:
import numpy as np

def is_valid(grid, row, col, num):
    """Check if placing num in grid[row][col] is valid."""
    # 1. Check the row using NumPy vectorization
    if num in grid[row, :]:
        return False
        
    # 2. Check the column using NumPy vectorization
    if num in grid[:, col]:
        return False
        
    # 3. Check the 3x3 subgrid using NumPy slicing
    start_row, start_col = 3 * (row // 3), 3 * (col // 3)
    subgrid = grid[start_row:start_row+3, start_col:start_col+3]
    if num in subgrid:
        return False
        
    return True

def solve_sudoku(grid):
    """Solve the Sudoku puzzle using backtracking."""
    # Find all empty spaces (where value is 0)
    empty_spaces = np.argwhere(grid == 0)
    
    # If no empty spaces remain, the puzzle is solved
    if len(empty_spaces) == 0:
        return True
        
    # Pick the first empty cell
    row, col = empty_spaces[0]
    
    # Try placing digits from 1 to 9
    for num in range(1, 10):
        if is_valid(grid, row, col, num):
            grid[row, col] = num  # Tentatively place the number
            
            if solve_sudoku(grid):  # Recurse
                return True
                
            grid[row, col] = 0  # Backtrack if the placement fails
            
    return False

# --- Example Usage ---
if __name__ == "__main__":
    # Define an unsolved Sudoku puzzle (0 represents empty cells)
    puzzle = np.array([
        [5, 3, 0, 0, 7, 0, 0, 0, 0],
        [6, 0, 0, 1, 9, 5, 0, 0, 0],
        [0, 9, 8, 0, 0, 0, 0, 6, 0],
        [8, 0, 0, 0, 6, 0, 0, 0, 3],
        [4, 0, 0, 8, 0, 3, 0, 0, 1],
        [7, 0, 0, 0, 2, 0, 0, 0, 6],
        [0, 6, 0, 0, 0, 0, 2, 8, 0],
        [0, 0, 0, 4, 1, 9, 0, 0, 5],
        [0, 0, 0, 0, 8, 0, 0, 7, 9]
    ])

    print("Original Sudoku Puzzle:")
    print(puzzle)
    print("\nSolving...\n")

    if solve_sudoku(puzzle):
        print("Solved Sudoku Grid:")
        print(puzzle)
    else:
        print("No solution exists for this Sudoku puzzle.")


Original Sudoku Puzzle:
[[5 3 0 0 7 0 0 0 0]
 [6 0 0 1 9 5 0 0 0]
 [0 9 8 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 8 0]
 [0 0 0 4 1 9 0 0 5]
 [0 0 0 0 8 0 0 7 9]]

Solving...

Solved Sudoku Grid:
[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
