In [ ]:
import numpy as np 
# Single random float 
random_float = np.random.rand() 
print("random_float:",random_float) 
# 1D array of random floats 
array_1d = np.random.rand(5) 
print("array_1d:",array_1d) 
# 2D array of random floats 
array_2d = np.random.rand(2, 3) 
print("array_2d:",array_2d) 
# 3D array of random floats 
array_3d = np.random.rand(2, 3, 4) 
print("array_3d:",array_3d) 

random_float: 0.00778454432975928
array_1d: [0.63450861 0.81759627 0.86143302 0.24377021 0.7664856 ]
array_2d: [[0.10725961 0.86640528 0.57023952]
 [0.78723857 0.14970344 0.17492568]]
array_3d: [[[0.45174213 0.84154228 0.59808629 0.89334442]
  [0.92150827 0.83318171 0.93552687 0.72042313]
  [0.12830045 0.84609427 0.04253749 0.73432631]]

 [[0.05277196 0.86278716 0.19186747 0.68964869]
  [0.89111318 0.26912086 0.51966523 0.23603586]
  [0.20227061 0.43545335 0.10497193 0.57476813]]]


In [11]:
empty_array = np.empty((2,4),dtype=int,order='F') 
print(empty_array)

[[25895968444448860 32370111954616435 31525476570497138 31244048838426721]
 [23925768161198147 28429466576683100 32651513914720368      463862825059]]
