In [ ]:
import pandas as pd 
print(pd.date_range('6/1/2025', periods=5)) #MM/DD/YY

DatetimeIndex(['2025-06-01', '2025-06-02', '2025-06-03', '2025-06-04',
               '2025-06-05'],
              dtype='datetime64[us]', freq='D')


In [5]:
df=pd.read_csv('dota.csv')
print(df.to_string())

     total_bill    tip     sex smoker   day    time  size
0         16.99   1.01  Female     No   Sun  Dinner     2
1         10.34   1.66    Male     No   Sun  Dinner     3
2         21.01   3.50    Male     No   Sun  Dinner     3
3         23.68   3.31    Male     No   Sun  Dinner     2
4         24.59   3.61  Female     No   Sun  Dinner     4
5         25.29   4.71    Male     No   Sun  Dinner     4
6          8.77   2.00    Male     No   Sun  Dinner     2
7         26.88   3.12    Male     No   Sun  Dinner     4
8         15.04   1.96    Male     No   Sun  Dinner     2
9         14.78   3.23    Male     No   Sun  Dinner     2
10        10.27   1.71    Male     No   Sun  Dinner     2
11        35.26   5.00  Female     No   Sun  Dinner     4
12        15.42   1.57    Male     No   Sun  Dinner     2
13        18.43   3.00    Male     No   Sun  Dinner     4
14        14.83   3.02  Female     No   Sun  Dinner     2
15        21.58   3.92    Male     No   Sun  Dinner     2
16        10.3

In [16]:
print('>> Check the number of maximum returned rows')
print(pd.options.display.max_rows);  print('\n')
print('>> Get a summary of the DataFrame (including data types and non-null values)')
print(df.info());                    print('\n')
print('>> Generate descriptive statistics for numerical columns. ')
print(df.describe());                print('\n')
print('>> Check the dimensions of the DataFrame (rows, columns)')
print(df.shape);                     print('\n')
print('>> View column names')
print(df.columns)

>> Check the number of maximum returned rows
60


>> Get a summary of the DataFrame (including data types and non-null values)
<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    str    
 3   smoker      244 non-null    str    
 4   day         244 non-null    str    
 5   time        244 non-null    str    
 6   size        244 non-null    int64  
dtypes: float64(2), int64(1), str(4)
memory usage: 13.5 KB
None


>> Generate descriptive statistics for numerical columns. 
       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2

In [17]:
print(df.head(3))
print(df.tail(4))

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
     total_bill   tip     sex smoker   day    time  size
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2


In [ ]:
print(df['day'].value_counts())
res=df[df['total_bill']>40]
print(res)

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64
     total_bill    tip     sex smoker   day    time  size
59        48.27   6.73    Male     No   Sat  Dinner     4
95        40.17   4.73    Male    Yes   Fri  Dinner     4
102       44.30   2.50  Female    Yes   Sat  Dinner     3
142       41.19   5.00    Male     No  Thur   Lunch     5
156       48.17   5.00    Male     No   Sun  Dinner     6
170       50.81  10.00    Male    Yes   Sat  Dinner     3
182       45.35   3.50    Male    Yes   Sun  Dinner     3
184       40.55   3.00    Male    Yes   Sun  Dinner     2
197       43.11   5.00  Female    Yes  Thur   Lunch     4
212       48.33   9.00    Male     No   Sat  Dinner     4


R E A D I N G - C S V : -

In [ ]:
import pandas as pd 
df = pd.read_csv('data.csv') 
print(df)

   Name          email        mobile
0   ABC  email@som.com  998877665543
1   XYZ   qwsa@saa.com  534522522523
2  ABC2  email@som.com  998877665543
3   NaN   qwsa@saa.com  534522522523
4  ABC3  email@som.com  998877665543
5  XYZ3            NaN  534522522523
6  ABC4  email@som.com  998877665543
7  XYZ4            NaN  534522522523
8  ABC5  email@som.com  998877665543
9  XYZ5            NaN  534522522523


In [89]:
print(df['Name'].value_counts());  print('\n')
print(pd.options.display.max_rows);  print('\n')
print(df.info());                    print('\n')
print(df.describe());                print('\n')
print(df.shape);                     print('\n')
print(df.columns)

Name
ABC     1
XYZ     1
ABC2    1
ABC3    1
XYZ3    1
ABC4    1
XYZ4    1
ABC5    1
XYZ5    1
Name: count, dtype: int64


60


<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    9 non-null      str  
 1   email   7 non-null      str  
 2   mobile  10 non-null     int64
dtypes: int64(1), str(2)
memory usage: 372.0 bytes
None


             mobile
count  1.000000e+01
mean   7.667001e+11
std    2.447366e+11
min    5.345225e+11
25%    5.345225e+11
50%    7.667001e+11
75%    9.988777e+11
max    9.988777e+11


(10, 3)


Index(['Name', 'email', 'mobile'], dtype='str')


In [90]:
removed_rows = df[df.isna().any(axis=1)]
print(removed_rows)

   Name         email        mobile
3   NaN  qwsa@saa.com  534522522523
5  XYZ3           NaN  534522522523
7  XYZ4           NaN  534522522523
9  XYZ5           NaN  534522522523


In [91]:
ndf = df.dropna() 
print(ndf.to_string()) 
df.dropna(inplace = True)
print(df.to_string()) 

   Name          email        mobile
0   ABC  email@som.com  998877665543
1   XYZ   qwsa@saa.com  534522522523
2  ABC2  email@som.com  998877665543
4  ABC3  email@som.com  998877665543
6  ABC4  email@som.com  998877665543
8  ABC5  email@som.com  998877665543
   Name          email        mobile
0   ABC  email@som.com  998877665543
1   XYZ   qwsa@saa.com  534522522523
2  ABC2  email@som.com  998877665543
4  ABC3  email@som.com  998877665543
6  ABC4  email@som.com  998877665543
8  ABC5  email@som.com  998877665543


In [93]:
x = df["mobile"].median() 
df.fillna({"mobile": x}, inplace=True) 
print(x)

x = df["mobile"].mode()[0] 
df.fillna({"mobile": x}, inplace=True) 
print(x)

998877665543.0
998877665543


R E A D I N G - J S O N : -

In [ ]:
import pandas as pd 
df = pd.read_json('jata.json') 
print(df)

                       name   language                id  \
0             Adeel Solangi        NaN  V59OF92YF627HFY0   
1             Afzal Ghaffar     Sindhi  ENTOCR13RSCLZ6KU   
2             Aamir Solangi     Sindhi  IAKPO3R4761JDRVG   
3             Abla Dilmurat     Uyghur  5ZVOEPMJUI4MB4EN   
4                  Adil Eli     Uyghur  6VTI8X6LL0MMPJCC   
..                      ...        ...               ...   
192  Kristín Sigurðardóttir  Icelandic  ZP5TBBYX6RI2UJ31   
193            Rohini Vasav      Hindi  UEFML43TCGS04KWM   
194            Sunil Kapoor      Hindi  VY2A0APGVHK5NAW2   
195          Zamokuhle Zulu    isiZulu  XU7BX2F8M5PVZ1EF   
196           Bhupesh Menon      Hindi  0CEPNRDV98KT3ORP   

                                                   bio  version  
0    Donec lobortis eleifend condimentum. Cras dict...     6.10  
1    Aliquam sollicitudin ante ligula, eget malesua...     1.88  
2    Vestibulum pharetra libero et velit gravida eu...     7.27  
3    Donec lobo

In [77]:
print(df['language'].value_counts());  print('\n')
print(pd.options.display.max_rows);  print('\n')
print(df.info());                    print('\n')
print(df.describe());                print('\n')
print(df.shape);                     print('\n')
print(df.columns)

language
Hindi               41
Uyghur              20
Maltese             20
Sesotho sa Leboa    20
Galician            19
Sindhi              18
Icelandic           16
Setswana            16
Bosnian             14
isiZulu             12
Name: count, dtype: int64


60


<class 'pandas.DataFrame'>
RangeIndex: 197 entries, 0 to 196
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   name      197 non-null    str    
 1   language  196 non-null    str    
 2   id        197 non-null    str    
 3   bio       197 non-null    str    
 4   version   197 non-null    float64
dtypes: float64(1), str(4)
memory usage: 7.8 KB
None


          version
count  197.000000
mean     5.605838
std      2.590350
min      1.010000
25%      3.600000
50%      5.360000
75%      7.860000
max      9.990000


(197, 5)


Index(['name', 'language', 'id', 'bio', 'version'], dtype='str')


In [78]:
removed_rows = df[df.isna().any(axis=1)]
print(removed_rows)

            name language                id  \
0  Adeel Solangi      NaN  V59OF92YF627HFY0   

                                                 bio  version  
0  Donec lobortis eleifend condimentum. Cras dict...      6.1  


In [79]:
ndf = df.dropna() 
print(ndf.to_string()) 
df.dropna(inplace = True)
print(df.to_string())

                       name          language                id                                                                                                                                                                                                                                                                                                                                                                                                bio  version
1             Afzal Ghaffar            Sindhi  ENTOCR13RSCLZ6KU                                                                                                                                                                Aliquam sollicitudin ante ligula, eget malesuada nibh efficitur et. Pellentesque massa sem, scelerisque sit amet odio id, cursus tempor urna. Etiam congue dignissim volutpat. Vestibulum pharetra libero et velit gravida euismod.     1.88
2             Aamir Solangi            Sindhi  IAKPO3R4761JDRVG                 

 N U M P Y : - 

In [94]:
import numpy as np
print(np.__version__)

2.4.5


In [104]:
#2D ARRAY
b=np.array([[1,2],[3,4],[2.3,'A']])
print(b, type(b), b.dtype)

[['1' '2']
 ['3' '4']
 ['2.3' 'A']] <class 'numpy.ndarray'> <U32


In [122]:
p=np.ones(((4,3,1)))
print(p, type(p), p.dtype)

[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]] <class 'numpy.ndarray'> float64


In [129]:
array_F=np.ones(((3,4,6)),order='F')
print(array_F, type(array_F),array_F.dtype)

[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]] <class 'numpy.ndarray'> float64


In [ ]:
a=np.arange(-70,60,21) #start,end,step-size
a

array([-70, -49, -28,  -7,  14,  35,  56])

In [156]:
e=np.linspace(0,10,num=11,retstep=True) #start,end,required_no_inbtw,calculated-stepsize
e

(array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 np.float64(1.0))