In [1]:
import numpy as np
one_d=np.array([1,2,3])
two_d=np.array([[4,5,6]])
combined=np.vstack((two_d,one_d))
print("One Dimensional Array:")
print(one_d)
print("Two Dimensional Array:")
print(two_d)
print("Combined Array:")
print(combined)

One Dimensional Array:
[1 2 3]
Two Dimensional Array:
[[4 5 6]]
Combined Array:
[[4 5 6]
 [1 2 3]]


In [2]:
import numpy as np
array_2d=np.array([[1,2,3],[4,5,6]])
flattened_array=array_2d.flatten()
print("Original 2D Array:")
print(array_2d)
print("Flattened 1D Array:")
print(flattened_array)

Original 2D Array:
[[1 2 3]
 [4 5 6]]
Flattened 1D Array:
[1 2 3 4 5 6]


In [3]:
import numpy as np
arr=np.array([10,20,30,40,50])
reversed_arr=arr[::-1]
print("Original Array:")
print(arr)
print("Reversed Array:")
print(reversed_arr)

Original Array:
[10 20 30 40 50]
Reversed Array:
[50 40 30 20 10]


In [4]:
import numpy as np
arr1=np.array([[2,4,6],[8,10,12]])
arr2=np.array([[1,2,3],[4,5,6]])
print("Array 1:")
print(arr1)
print("Array 2:")
print(arr2)
print("Maximum Value:")
print(np.max(arr1))
print("Minimum Value:")
print(np.min(arr1))
rows,columns=arr1.shape
print("Rows:",rows)
print("Columns:",columns)
print("All Elements:")
for row in arr1:
    for element in row:
        print(element,end=" ")
print()
print("Specific Element:")
print(arr1[1][2])
sum_value=0
for row in arr1:
    for element in row:
        sum_value+=element
print("Sum of Elements:")
print(sum_value)
print("Addition:")
print(arr1+arr2)
print("Subtraction:")
print(arr1-arr2)
print("Multiplication:")
print(arr1*arr2)
print("Division:")
print(arr1/arr2)

Array 1:
[[ 2  4  6]
 [ 8 10 12]]
Array 2:
[[1 2 3]
 [4 5 6]]
Maximum Value:
12
Minimum Value:
2
Rows: 2
Columns: 3
All Elements:
2 4 6 8 10 12 
Specific Element:
12
Sum of Elements:
42
Addition:
[[ 3  6  9]
 [12 15 18]]
Subtraction:
[[1 2 3]
 [4 5 6]]
Multiplication:
[[ 2  8 18]
 [32 50 72]]
Division:
[[2. 2. 2.]
 [2. 2. 2.]]


In [5]:
import numpy as np
array_3d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("3D Array:")
print(array_3d)
print("Iteration using for loop:")
for matrix in array_3d:
    for row in matrix:
        for element in row:
            print(element)
print("Iteration using nditer:")
for element in np.nditer(array_3d):
    print(element)

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Iteration using for loop:
1
2
3
4
5
6
7
8
Iteration using nditer:
1
2
3
4
5
6
7
8


In [6]:
import numpy as np
from statistics import mode
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[6,5,4],[3,2,1]])
print("Array 1:")
print(arr1)
print("Array 2:")
print(arr2)
average=(arr1+arr2)/2
print("Average of Arrays:")
print(average)
combined_array=np.concatenate((arr1.flatten(),arr2.flatten()))
mean_value=np.mean(combined_array)
median_value=np.median(combined_array)
mode_value=mode(combined_array)
print("Mean Value:")
print(mean_value)
print("Median Value:")
print(median_value)
print("Mode Value:")
print(mode_value)

Array 1:
[[1 2 3]
 [4 5 6]]
Array 2:
[[6 5 4]
 [3 2 1]]
Average of Arrays:
[[3.5 3.5 3.5]
 [3.5 3.5 3.5]]
Mean Value:
3.5
Median Value:
3.5
Mode Value:
1
