In [1]:
import numpy as np
arr = np.array([14, 28, 42, 56, 70, 84])
print(arr)

[14 28 42 56 70 84]


In [2]:
arr_2d = arr.reshape(2, 3)
print(arr_2d)

[[14 28 42]
 [56 70 84]]


In [3]:
print("Shape:", arr_2d.shape)
print("Dimension:", arr_2d.ndim)
print("Data Type:", arr_2d.dtype)
print("Item Size:", arr_2d.itemsize)

Shape: (2, 3)
Dimension: 2
Data Type: int64
Item Size: 8


In [4]:
nines = np.full((3, 3), 9)
print(nines)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [5]:
even_space = np.linspace(25, 125, 10)
print(even_space)

[ 25.          36.11111111  47.22222222  58.33333333  69.44444444
  80.55555556  91.66666667 102.77777778 113.88888889 125.        ]


In [6]:
values = [18, 36, 54, 72, 90]
list_array = np.array(values)
print(list_array)

[18 36 54 72 90]


In [7]:
print(list_array[::-1])

[90 72 54 36 18]


In [8]:
cube = np.arange(101, 149).reshape(4, 4, 3)
print(cube[1, 0, 2])

115


In [9]:
grid = np.arange(1, 17).reshape(4, 4)
print(grid[0::2, 1::2])

[[ 2  4]
 [10 12]]


In [10]:
print(cube[1, :2, :2])

[[113 114]
 [116 117]]


In [11]:
data = np.array([[23, 56, 78, 93], [71, 82, 13, 24]])
for i in range(data.shape[0]):
    for j in range(data.shape[1]):
        if data[i, j] % 2 != 0:
            data[i, j] = -1
print(data)

[[-1 56 78 -1]
 [-1 82 -1 24]]


In [12]:
numbers = np.array([1, 0, 2, 0, 3, 0, 4])
print(np.nonzero(numbers))

(array([0, 2, 4, 6]),)


In [13]:
first = np.array([12, 24, 36, 48])
second = np.array([5, 10, 15, 20])
print(first + second)
print(first * second)

[17 34 51 68]
[ 60 240 540 960]


In [14]:
arr1 = np.array([15, 20, 25])
arr2 = np.array([10, 40, 37])
print(np.dot(arr1, arr2))

1875
