In [9]:
import numpy as np
a = np.array([[6, -8, 73, -110], [np.nan, -8, 0, 94]])
a = np.nan_to_num(a, nan=0)
r = a[[1, 0]]
c = a[:, [3, 2, 1, 0]]
print(r)
print(c)

[[   0.   -8.    0.   94.]
 [   6.   -8.   73. -110.]]
[[-110.   73.   -8.    6.]
 [  94.    0.   -8.    0.]]


In [10]:
import numpy as np
a = np.arange(24).reshape(2, 3, 4)
b = np.moveaxis(a, 0, 2)
print(b)

[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]


In [11]:
import numpy as np
a = np.array([
    [4, np.nan, 7],
    [2, 5, np.nan],
    [6, 8, 9]
])
m = np.nanmean(a, axis=0)
i = np.where(np.isnan(a))
a[i] = np.take(m, i[1])
print(a)

[[4.  6.5 7. ]
 [2.  5.  8. ]
 [6.  8.  9. ]]


In [12]:
import numpy as np
a = np.array([4, -3, 7, -1, 0, -9])
a = np.where(a < 0, 0, a)
print(a)

[4 0 7 0 0 0]
